server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml,text/plain,text/css,application/javascript
    min-response-size: 1024

spring:
  application:
    name: movie-ticket-backend

  datasource:
    url: jdbc:mysql://localhost:3306/movieticket?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Nitin@2004
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: nitindiwewar0@gmail.com
    password: hddygbsicnmqvuun
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000

  cors:
    allowed-origins: "http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173"

tmdb:
  api-key: e01d0966ebcead42f3a3bec84c24b41d
  base-url: https://api.themoviedb.org/3
  image-base-url: https://image.tmdb.org/t/p

razorpay:
  key-id: rzp_test_TJJY5Q4lsHDjQL
  key-secret: wcoypHqN2jd0V23A5y3dweV8

sms:
  fast2sms:
    api-key: gNDESxRv5IHj37KGeBFCdcuYXslOq4n8k1btUTVaM9frph6zLPlcdEiPUoNu5DxmJfXhpV8OegtBRkTS
