server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml,text/plain,text/css,application/javascript
    min-response-size: 1024

spring:
  application:
    name: movie-ticket-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:nitindiwewar0@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:hddygbsicnmqvuun}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000

  cors:
    allowed-origins: "http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173"

tmdb:
  api-key: ${TMDB_API_KEY:e01d0966ebcead42f3a3bec84c24b41d}
  base-url: https://api.themoviedb.org/3
  image-base-url: https://image.tmdb.org/t/p

razorpay:
  key-id: ${RAZORPAY_KEY_ID:rzp_test_TJJY5Q4lsHDjQL}
  key-secret: ${RAZORPAY_KEY_SECRET:wcoypHqN2jd0V23A5y3dweV8}

sms:
  fast2sms:
    api-key: ${FAST2SMS_API_KEY:gNDESxRv5IHj37KGeBFCdcuYXslOq4n8k1btUTVaM9frph6zLPlcdEiPUoNu5DxmJfXhpV8OegtBRkTS}
